# Generated by Django 3.0.7 on 2020-10-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='istied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='layout',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='board',
            name='loser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='user1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='user2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='winner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='losses',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='ties',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='wins',
            field=models.IntegerField(blank=True),
        ),
    ]
